pipeline {
    agent { label 'agent1-ubuntu' }

    parameters {
        choice choices: ['javaapp-pipeline', 'javaapp-standalone', 'javaapp-tomcat'], name: 'folder'
        booleanParam defaultValue: true, description: 'enable to deploy the package on an agent ', name: 'DEPLOY'
    }

    stages {

        /* ----------------------------
         * COMMON FOR ALL BRANCHES
         * ---------------------------- */

        stage('Checkout') {
            steps {
                git 'https://github.com/darninidhi-2122/jenkins-practice.git'
            }
        }

        stage('Debug Parameters') {
           steps {
              echo "Folder param = ${params.folder}"
              echo "Deploy param = ${params.DEPLOY}"
    }
}
        stage('Quality Checks in Parallel') {
            parallel {

                stage('Unit Tests') {
                    steps {
                        dir("${folder}") {
                            sh "mvn clean test"
                        }
                    }
                }

                stage('Trivy Scan') {
                    steps {
                        sh """
                            wget -q -O html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
                            trivy fs . --format template --template "@html.tpl" -o report.html
                        """
                    }
                }

            }
        }

        /* ----------------------------
         * ONLY FOR main BRANCH
         * ---------------------------- */

        stage('Build') {
            when { branch "main" }
            steps {
                dir("${folder}") {
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('SonarQube analysis') {
            when { branch "main" }
            steps {
                dir("${folder}") {
                    withSonarQubeEnv('sonar') {
                        sh """
                            mvn clean verify sonar:sonar \
                            -Dsonar.projectKey=java-app \
                            -Dsonar.projectName=java-app
                        """
                    }
                }
            }
        }

        /* ----------------------------
         * APPROVAL STEP
         * ---------------------------- */

        stage('Approval for Deployment') {
            when { branch "main" }
            steps {
                script {
                    timeout(time: 5, unit: 'MINUTES') {
                        input(
                            message: "Approve Deployment?",
                            ok: "Deploy Now",
                            submitter: "darninidhi-2122"
                        )
                    }
                }
            }
        }

        stage('Deploy to Server') {
            when { allOf { branch "main"; expression { params.DEPLOY == true } } }
            steps {
                dir("${folder}/target") {
                    sh '''
                        if pgrep -f "java -jar java-sample-21-1.0.0.jar" > /dev/null; then
                            pkill -f "java -jar java-sample-21-1.0.0.jar"
                            echo "app was running and has been killed"
                        else
                            echo "app is not running"
                        fi

                        JENKINS_NODE_COOKIE=dontKillMe nohup java -jar java-sample-21-1.0.0.jar > app.log 2>&1 &
                    '''
                }
            }
        }

    }

    post {
        always {
            echo "Cleaning workspace..."
            cleanWs()
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
            emailext body: 'Build failed', subject: 'Build Failure', to: 'darni.nidhi@gmail.com'
        }
    }
}
